Spint 2/step 2
Anatoos/react-burger pull request #2
Opened 2022-10-01 21:45 UTC by Anatoos

2022-10-01 22:33 UTC, ArslanDev666 requested changes
## Code Review

### Работа отклоняется, т.к проект не запускается и не билдится.

2022-10-02 15:39 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Хорошая работа.

### **Вы молодцы!**

- Декомпозиция файлов по директориям - практически соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Реализован функционал компонента Popup с помощью Portals;
- Реализован контент в компоненте Popup через children;

### **Но есть несколько замечаний, которые нужно исправить:**

- Компонент `OrderDetails` не соответствует макету;

- Конструктор бургера не соответствует макету;
   
   ![image](https://user-images.githubusercontent.com/70164458/193462671-b7185ebb-d21e-4a24-a585-ac0f63230387.png)

- По чек-листу требуется, чтобы при скролле внутри компонента BurgerIngredients самый ближний к верхней левой границе заголовок контейнера становится активным;

- Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`
  Например
  ```
  <a href="#" class="......">
    <BurgerIcon type="primary" /> Конструктор
  </a>
  ```
  В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой;

- По чек листу требуется чтобы для каждого экшена, который связан с запросом к Api создан усилитель. Для таких экшенов описан тип _REQUEST, тип _SUCCESS, _ERROR. Добавьте у себя `_REQUEST` там где это требуется.

- В консоли есть ошибки;
### **Сделает код лучше:**

- Перед отправкой работы убедитесь в том, что весь неиспользуемый код удален.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами и в некоторых местах слишком длинные строки, что затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

### **_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-10-02 15:39 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SelectedItems/SelectedItems.jsx
> +const SelectedItems = (props) => {
**Можно лучше:** Лучше применить Деструктуризацию, там будет понятнее какие пропсы вы передаёте.

2022-10-02 15:39 UTC, ArslanMustafin commented on src/components/BurgerConstructor/SelectedItems/SelectedItems.jsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
**Можно лучше:** Вроде тут можно не выключать eslint, он не кидает ошибки.

2022-10-02 15:39 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +    const hoverPosition = useSelector(state => state.constructorOrder.hoverBoundingRect)
**Можно лучше:** Можно сократить до 2 `useSelector`, с помощью деструктуризации.
```js 
    const {
        selectedBun: bun,
        hoverBoundingRect: hoverPosition,
        selectedItems,
    } = useSelector((state) => state.constructorOrder);
```

2022-10-02 15:39 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        selectedItems.map((item) => result.ingredients.push(item._id));
**Надо исправить:** Тут лучше использовать forEach.
forEach: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
map: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/map

2022-10-02 15:39 UTC, ArslanDev666 commented on src/services/reducers/constructor.js
> +            state.selectedItems.splice(indexTo, 0, item)
**Надо исправить :** Лучше не мутировать состояние state напрямую. Попробуйте вынести в отдельную переменную selectedItems.
И уже с ней можно делать всё что угодно.
```js 
const selectedItems = [...state.selectedItems];
```

2022-10-02 15:39 UTC, ArslanDev666 commented on src/services/reducers/ingredient.js
> +            }
**Надо исправить:** Массивы это ссылочный тип данных в js, поэтому таким образом вы будете изменять исходный массив state.ingredientsData, а это нежелательно делать. Чтобы этого избежать, можно воспользоваться spread оператором.

```js 
const arr = [...state.ingredientsData]
```

2022-10-02 15:39 UTC, ArslanDev666 commented on src/services/reducers/ingredient.js
> +        case GET_INGREDIENT: {
**Надо исправить:** Здесь и далее. По чек листу требуется чтобы для каждого экшена, который связан с запросом к Api создан усилитель. Для таких экшенов описан тип _REQUEST, тип _SUCCESS, _ERROR. Добавьте сюда `_REQUEST`.

2022-10-02 15:39 UTC, ArslanDev666 commented on src/components/BurgerIgredients/BurgerIngredients.jsx
> +        window.history.pushState(null,null,'/ingredients/' + findElement(id)._id);
**Надо исправить:** Здесь и ниже. Т.к это реакт, а в будущем вы будете использовать React-router,то лучше этого не делать, т.к это может вызвать баги и неверный рендер страницы.  
Вот тут неплохое обсуждение этой проблемы. https://stackoverflow.com/questions/59567134/what-differences-between-link-in-react-router-and-window-history-pushstate

2022-10-02 15:59 UTC, Anatoos commented
> Дизайн не соответствует макету
> Есть в консоли ошибки

Добрый день! Спасибо за проверку.
Но я не могу понять какие ошибки и почему у Вас выглядит так.
![image](https://user-images.githubusercontent.com/108093605/193463651-d5a8349a-e3f5-40e3-8300-573afb6da662.png)

У меня нет ошибок и дизайн корректно отображается.

2022-10-02 16:08 UTC, Anatoos commented
> > Дизайн не соответствует макету
> > Есть в консоли ошибки
> 
> Добрый день! Спасибо за проверку. Но я не могу понять какие ошибки и почему у Вас выглядит так. ![image](https://user-images.githubusercontent.com/108093605/193463651-d5a8349a-e3f5-40e3-8300-573afb6da662.png)
> 
> У меня нет ошибок и дизайн корректно отображается.

Я с момента отправки на ревью много чего поправил.
Я сейчас удалил node modules, сделал rebase от текущей версии sprint-2/step-2 и по новой npm install, всё равно ни ошибок ни проблем в дизайне

2022-10-02 16:21 UTC, Anatoos commented on src/components/BurgerConstructor/SelectedItems/SelectedItems.jsx
> +    // eslint-disable-next-line react-hooks/rules-of-hooks
Исправлено

2022-10-02 16:21 UTC, Anatoos commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +        selectedItems.map((item) => result.ingredients.push(item._id));
Исправлено

2022-10-02 16:21 UTC, Anatoos commented on src/services/reducers/constructor.js
> +            state.selectedItems.splice(indexTo, 0, item)
Исправлено

2022-10-02 16:21 UTC, Anatoos commented on src/services/reducers/ingredient.js
> +            }
Исправлено

2022-10-02 16:22 UTC, Anatoos commented on src/services/reducers/ingredient.js
> +        case GET_INGREDIENT: {
Исправлено

2022-10-02 16:44 UTC, Anatoos commented on src/components/BurgerIgredients/BurgerIngredients.jsx
> +        window.history.pushState(null,null,'/ingredients/' + findElement(id)._id);
Убрал впринципе рутинг, пока не нужен.

2022-10-02 20:20 UTC, ArslanDev666 commented
> > > Дизайн не соответствует макету
> > > Есть в консоли ошибки
> > 
> > 
> > Добрый день! Спасибо за проверку. Но я не могу понять какие ошибки и почему у Вас выглядит так. ![image](https://user-images.githubusercontent.com/108093605/193463651-d5a8349a-e3f5-40e3-8300-573afb6da662.png)
> > У меня нет ошибок и дизайн корректно отображается.
> 
> Я с момента отправки на ревью много чего поправил. Я сейчас удалил node modules, сделал rebase от текущей версии sprint-2/step-2 и по новой npm install, всё равно ни ошибок ни проблем в дизайне

Я посмотрю еще раз, и попробую разобраться, может действительно с моей стороны какие-то баги.

2022-10-03 12:56 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодцы!**

- Все замечания с прошлого ревью, были исправлены.

### **Но есть 1 новое замечание, которое нужно исправить, в остальном всё отлично:**

- По чек-листу нужно, чтобы пользователь мог сортировать элементы в конструкторе - перетаскиванием. Сортировать элементы типа `bun` перетаскиванием нельзя. При перетаскивании элемента конструктора во вне ничего происходить не должно. 

- Очень странно ведёт себя счётчик на ингредиентах. 

Прикрепил видео: https://disk.yandex.ru/i/hNN86CmBVjqcMg

Видел что при перетаскивании есть взаимодействие с redux, но внешне элементы остаются на своих местах.

2022-10-03 13:18 UTC, ArslanDev666 commented
Отлично сортировка перетаскивание заработала, осталось понять что случилось со счётчиками у ингредиентов, я там видео добавил, чтобы было понятно, о чём я говорю.

2022-10-03 13:19 UTC, Anatoos commented
> Отлично, сортировка перетаскиванием заработала, осталось понять что случилось со счётчиками у ингредиентов, я там видео добавил, чтобы было понятно, о чём я говорю.

Хорошо, есть необходимость допиливать этот компонент?

2022-10-03 13:20 UTC, Anatoos commented
- [ ]

2022-10-03 13:20 UTC, Anatoos commented
Нетуда нажал извините

2022-10-03 13:21 UTC, ArslanDev666 commented
В идеале бы, исправить баг со счётчиком, и можно принимать проект.

2022-10-03 13:23 UTC, Anatoos commented
> В идеале бы, исправить баг со счётчиком, и можно принимать проект.

Я могу к сдаче третьего спринта это пофиксить? Мне нужно рефакторить целый компонент, который всё равно придётся рефакторить, чтобы рутинг на игредиентах работал.
 Просто желательно открыть программу третьего спринта

2022-10-03 13:24 UTC, Anatoos commented
Хочется к встрече по третьему спринту хотя бы посмотреть что от нас требуется, чтобы сразу задавать вопросы про библиотеки и про требования.

2022-10-03 13:38 UTC, Anatoos commented
> В идеале бы, исправить баг со счётчиком, и можно принимать проект.

Исправил. оказывается рефакторить ничего не нужно было, я думал проблема в том, что у меня зависимость шаблона стоит напрямую от блока с категорией ингредиентов. Оказывается была проблема CSS, на Counter стоит position:absolute. Ближайшая была как раз контейнер с категорией ингредиентов, думал в этом проблема, но т.к. у меня есть блок с ингредиентом я переставил зависимость position на неё, потому теперь Counter получается position:absolute в рамках position:relative от родительского блока.

2022-10-03 13:41 UTC, ArslanDev666 approved these changes
## Code Review

**Работа принята! 🔥🔥🔥 Удачи вам!**

### **Сделает код лучше:**

- Проблема счётчика действительно в верстке, а именно в том, что компонент Counter - имеет абсолютное позиционирование. Чтобы это пофиксить, достаточно задать `position: relative` родителю (`.item` в файле `BurgerIngredients.module.css`).

  Также, когда искал корни проблемы наткнулся на 1 кусок кода, и отписал как там лучше сделать.

2022-10-03 13:41 UTC, ArslanMustafin commented on src/services/reducers/ingredient.js
> +            }
**Можно лучше:** В данному случае, очень удобно использовать метод map.

```js 
  const updateIngredientsData = state.ingredientsData.map(ingredient => {
        if (ingredient._id === action.id) {
            ingredient.count += 1
        }
        return ingredient;
    })

    return {
        ...state,
        ingredientsData: updateIngredientsData
    }
```

У вас похожая реализация есть чуть ниже, в `DECREASE_ITEM_COUNT`.

2022-10-03 13:42 UTC, ArslanMustafin commented
> > В идеале бы, исправить баг со счётчиком, и можно принимать проект.
> 
> Исправил. оказывается рефакторить ничего не нужно было, я думал проблема в том, что у меня зависимость шаблона стоит напрямую от блока с категорией ингредиентов. Оказывается была проблема CSS, на Counter стоит position:absolute. Ближайшая была как раз контейнер с категорией ингредиентов, думал в этом проблема, но т.к. у меня есть блок с ингредиентом я переставил зависимость position на неё, потому теперь Counter получается position:absolute в рамках position:relative от родительского блока.

хех, вы меня опередили, но в любом случае, очень хорошо что вы разобрались. Кидайте на проверку задание, я его приму.

2022-10-03 13:44 UTC, Anatoos commented
> > > В идеале бы, исправить баг со счётчиком, и можно принимать проект.
> > 
> > 
> > Исправил. оказывается рефакторить ничего не нужно было, я думал проблема в том, что у меня зависимость шаблона стоит напрямую от блока с категорией ингредиентов. Оказывается была проблема CSS, на Counter стоит position:absolute. Ближайшая была как раз контейнер с категорией ингредиентов, думал в этом проблема, но т.к. у меня есть блок с ингредиентом я переставил зависимость position на неё, потому теперь Counter получается position:absolute в рамках position:relative от родительского блока.
> 
> хех, вы меня опередили, но в любом случае, очень хорошо что вы разобрались. Кидайте на проверку задание, я его приму.

Отправил

2022-10-03 13:55 UTC, merged